### ISSUE TITLE
Feature request: Redirect setting

### ISSUE THREAD

**Issue by NielsvandenDries** [rainlab/userplus-plugin#39] opened 2022-12-20 10:18 UTC
Hi Team,

Wouldn't it be great if you could set in the user group to which page the person who logged in is routed
;-)

**Comment by daftspunk** [comment] 2023-01-11 00:17
Duplicate of https://github.com/rainlab/user-plugin/issues/504

**Closed as completed by daftspunk** 2023-01-11 00:17 UTC
